export const LIFEWHEEL_REPOSITORY_TOKEN = 'LIFEWHEEL_REPOSITORY_TOKEN';
export const LIFEWHEEL_AREA_REPOSITORY_TOKEN =
  'LIFEWHEEL_AREA_REPOSITORY_TOKEN';
export const ANSWER_REPOSITORY_TOKEN = 'ANSWER_REPOSITORY_TOKEN';
